### ISSUE TITLE
Posts not appearing

### ISSUE THREAD

**Issue by torieketcham** [marinebon/www_marinebon2#13]
I'm adding news items as posts via the Wowchemy CMS and they aren't appearing on the site for some reason... I've waited for a while after each commit and cleared cache and still nothing. Attached are screenshots of the three posts within the CMS. 

I deleted and re-added the Marine Life 2030 post as well to remove the image of the dog, but it still seems to be appearing as well.

<img width="1296" alt="Screen Shot 2021-04-28 at 4 01 06 PM" src="https://user-images.githubusercontent.com/44508950/116465540-59ea5b80-a83b-11eb-87ff-8661efa450b5.png">

**Comment by 7yl4r** [comment]
Hmm. I was really hoping this would just work out of the box because I don't fully understand the details of it.
I am going to list out information here as I explore this so I we come back to these notes later if needed.

✔️ Folders and `index.md` files are getting correctly added to `/content/post`.
I'm pretty sure this is where they are supposed to be.

❔ I do not know how `/content/post/_index.md` works but I think this is what creates the aggregated posts view at https://marinebon2.netlify.app/post/. Right now only the one post (Marine Life 2030) is showing. 
Actually - weird: that post actually links to a "getting-started" url ( https://marinebon2.netlify.app/post/getting-started/ )... that does not align well with what I see in `/content/post/`.

❗ Let's check on the build status in netlify ([here](https://app.netlify.com/sites/marinebon2/deploys/6089be535aebb600078b732a)). 
Oh here we go - there is a build error: `config/_default/params.toml:151:1 [...] newlines not allowed within inline tables.
Oops. This is my fault. I broke this back in 579a230f0af0c11cbe1562455d22b0f8b730c768.

I will fix that then look back at this when things have built properly.

**Comment by 7yl4r** [comment]
There we go. 
All three posts now showing up on the homepage "recent news" section as well as on https://marinebon2.netlify.app/post/. 
The site just hadn't done a successful build since you made changes.

NOTE: we probably want to delete the `/content/post/getting-started` folder.
